FROM node:21-alpine3.17 AS build
WORKDIR /app
COPY ../client/ /app
RUN npm install
RUN npm run build

FROM nginx:alpine

# Copy the build files to the Nginx directory
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

